### ISSUE TITLE
Upload glossaries in the Backend module

### ISSUE THREAD

**Issue by helmut-winkelbach** [dmitryd/dd_deepl#18] opened 2024-03-08 14:04 UTC
If i try this function, i get the following error:
ArgumentCountError, 3 arguments are required, 2 given
The full stack trace:
`Fri, 08 Mar 2024 14:59:56 +0100 [CRITICAL] request="543ccc8eaefe5" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): ArgumentCountError, code #0, file /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Utility/LocalizationUtility.php, line 91: 3 arguments are required, 2 given- ArgumentCountError: 3 arguments are required, 2 given, in file /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Utility/LocalizationUtility.php:91 - {"mode":"WEB","application_mode":"BE","exception_class":"ArgumentCountError","exception_code":0,"file":"/var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Utility/LocalizationUtility.php","line":91,"message":"3 arguments are required, 2 given","request_url":"https://...-web.de/typo3/module/site/DdDeepl/?token=--AnonymizedToken--&id=243&action=upload","exception":"ArgumentCountError: 3 arguments are required, 2 given in /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Utility/LocalizationUtility.php:91\nStack trace:\n#0 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Utility/LocalizationUtility.php(91): sprintf()\n#1 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/dmitryd/dd-deepl/Classes/Controller/BackendModuleController.php(287): TYPO3\\CMS\\Extbase\\Utility\\LocalizationUtility::translate()\n#2 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(479): Dmitryd\\DdDeepl\\Controller\\BackendModuleController->uploadAction()\n#3 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(396): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#4 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Mvc/Dispatcher.php(68): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest()\n#5 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-extbase/Classes/Core/Bootstrap.php(230): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch()\n#6 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Http/RouteDispatcher.php(77): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleBackendRequest()\n#7 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Http/RequestHandler.php(104): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch()\n#8 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle()\n#9 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process()\n#10 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/SiteResolver.php(64): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#11 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process()\n#12 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/SudoModeInterceptor.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#13 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SudoModeInterceptor->process()\n#14 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/AdditionalResponseHeaders.php(37): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process()\n#16 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyHeaders.php(50): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyHeaders->process()\n#18 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/OutputCompression.php(43): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process()\n#20 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/BackendModuleValidator.php(194): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendModuleValidator->process()\n#22 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/BackendUserAuthenticator.php(159): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#23 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process()\n#24 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Middleware/RequestTokenMiddleware.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#25 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\RequestTokenMiddleware->process()\n#26 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/BackendRouteInitialization.php(80): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#27 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process()\n#28 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyReporter.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#29 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyReporter->process()\n#30 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#31 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process()\n#32 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Middleware/LockedBackendGuard.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#33 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process()\n#34 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#35 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process()\n#36 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#37 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process()\n#38 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#39 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(80): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()\n#40 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-backend/Classes/Http/Application.php(58): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()\n#41 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(92): TYPO3\\CMS\\Backend\\Http\\Application->handle()\n#42 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/public/typo3/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#43 /var/www/vhosts/...-hosting.de/httpdocs/...-web.de/public/typo3/index.php(21): {closure}()\n#44 {main}"}
`

**Comment by helmut-winkelbach** [comment] 2024-03-13 07:40
Hi Dmitry!
The upload works perfectly with the corrected glossary file.

**Comment by dmitryd** [comment] 2024-03-13 08:01
Thanks! I still need to find what was the cause of the exception though...

**Comment by dmitryd** [comment] 2024-03-25 18:10
This is fixed with af94cc0ec798774a5775502c545dfcb065dee285 and will be in the release next to 12.5.0

**Closed by dmitryd** 2024-03-25 18:10 UTC
